name: Bug Report
description: "Make sure to read through all instructions in the template below before submitting an issue."
labels: ["bug"]
body:
    - type: checkboxes
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an open or closed issue already exists for the bug you encountered. If a bug exists and it is closed as complete it may not yet be in a stable release.
          options:
              - label: I have searched the existing open and closed issues
                required: true
    - type: textarea
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: false
    - type: textarea
      attributes:
          label: Environment
          description: |
              examples:
                - **AniBridge**: AniBridge 2.0.0
                - **OS**: Ubuntu 24.04
                - **Docker Install**: Yes
          value: |
              - AniBridge:
              - OS:
              - Docker Install:
          render: markdown
      validations:
          required: true
    - type: dropdown
      attributes:
          label: What branch are you running?
          options:
              - Main
              - Develop
              - Other (This issue will likely be closed)
      validations:
          required: true
    - type: textarea
      attributes:
          label: Configuration
          description: |
              Paste your AniBridge configuration here. Make sure to redact any sensitive information. Generally, omitting the `list_provider_config`, `library_provider_config`, and `web.basic_auth` sections of your configuration is sufficient to redact sensitive information.
          render: yaml
      validations:
          required: true
    - type: textarea
      attributes:
          label: Debug Logs?
          description: |
              Generally speaking, all bug reports must have debug logs provided (from a file like `*.DEBUG.log`). If you do not provide debug logs and the issue is not easily reproducible, your issue may be closed until you can provide debug logs.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? Screenshots? References? Anything that will give us more context about the issue you are encountering!
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
