"""make scope optional

Revision ID: ff7071ae23d8
Revises: 5daf8f33a740
Create Date: 2026-01-17 03:56:34.238060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7071ae23d8'
down_revision: Union[str, None] = '5daf8f33a740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_entry', schema=None) as batch_op:
        batch_op.alter_column('entry_scope',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_entry', schema=None) as batch_op:
        batch_op.alter_column('entry_scope',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
