"""Animap entry indexing

Revision ID: 38ae72352337
Revises: ff7071ae23d8
Create Date: 2026-01-26 07:37:23.429910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ae72352337'
down_revision: Union[str, None] = 'ff7071ae23d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_animap_mapping_destination_source', ['destination_entry_id', 'source_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_mapping', schema=None) as batch_op:
        batch_op.drop_index('ix_animap_mapping_destination_source')

    # ### end Alembic commands ###
