"""Add ephemeral flag to sync history

Revision ID: 48fc289f8e59
Revises: 0b5e4f0b749e
Create Date: 2026-03-27 19:29:58.284996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fc289f8e59'
down_revision: Union[str, None] = '0b5e4f0b749e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new 'ephemeral' as nullable first so we can backfill existing rows
    op.add_column("sync_history", sa.Column("ephemeral", sa.Boolean(), nullable=True))
    op.execute("UPDATE sync_history SET ephemeral = false")

    with op.batch_alter_table("sync_history", schema=None) as batch_op:
        batch_op.alter_column("ephemeral", nullable=False)
        batch_op.create_index(batch_op.f("ix_sync_history_ephemeral"), ["ephemeral"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_history_ephemeral'))
        batch_op.drop_column('ephemeral')

    # ### end Alembic commands ###
